variable "ec2_type" {}
variable "ec2_name" {}
variable "instance_count" {}
variable "db_allocated_storage" {}
variable "db_username" {}
variable "db_password" {}
variable "region" {}
variable "tags" {}
variable "ec2_ami" {}
variable "my_vpc_tag" {}
variable "my_subnet_tag" {}
variable "vpc_cidr_block" {}
variable "subnet_cidr_block" {}